/* ==========================================================================
   PRODUCTS DATASET — BUFFALO MANUFACTURA ARQUITECTÓNICA
   Core Specialization: CELOSÍAS ARQUITECTÓNICAS & CATÁLOGO DE COLECCIONES
   Contiene todas las 62 imágenes organizadas en assets/
   ========================================================================== */

const BUFFALO_PRODUCTS = [
  {
    "id": "prod-cel-001",
    "name": "Celos\u00eda de Roble Macizo y Nogal",
    "category": "celosias",
    "categoryName": "Celos\u00edas Arquitect\u00f3nicas",
    "price": 4800,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/celosias/CELOSIA_MADERA.jpg",
    "gallery": [
      "assets/celosias/Black_metal_perimeter_lattice_wall_2K_20261002132212.jpg",
      "assets/celosias/CELOSIA_MADERA.jpg",
      "assets/celosias/Change_lattice_pattern_2K_20261002093222.jpg",
      "assets/celosias/Geometric_metal_partition_wall_d_2K_20261002124111.jpg"
    ],
    "description": "Celos\u00eda de madera maciza seleccionada con maquiado de precisi\u00f3n CNC. Dise\u00f1o ideal para divisiones de \u00e1reas y cielos celos\u00eda.",
    "available": true,
    "customizable": true,
    "sku": "BUF-CEL-001",
    "material": "Roble Blanco / Nogal Seleccionado",
    "dimensions": "Paneles de 120 x 240 cm (Espesor 25mm)",
    "leadTime": "12 a 15 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Celos\u00eda Destacada"
  },
  {
    "id": "prod-cel-002",
    "name": "Celos\u00eda Perimetral Negra Met\u00e1lica",
    "category": "celosias",
    "categoryName": "Celos\u00edas Arquitect\u00f3nicas",
    "price": 3900,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/celosias/Black_metal_perimeter_lattice_wall_2K_20261002132212.jpg",
    "gallery": [
      "assets/celosias/Green_wall_with_metal_lattice_2K_20261002133847.jpg",
      "assets/celosias/Lattice_screen_on_stone_wall_2K_20261002132138.jpg",
      "assets/celosias/Modern_partition_wall_with_geome_2K_20261002124119.jpg",
      "assets/celosias/Suspended_wood_lattice_ceiling_d_2K_20261002115906.jpg"
    ],
    "description": "Panel celos\u00eda met\u00e1lico termoenmarcado con pintura electrost\u00e1tica de alta resistencia a intemperie.",
    "available": true,
    "customizable": true,
    "sku": "BUF-CEL-002",
    "material": "Acero / Aluminio Anodizado Negro",
    "dimensions": "Paneles 100 x 200 cm o a medida",
    "leadTime": "10 a 14 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Exterior & Interior"
  },
  {
    "id": "prod-cel-003",
    "name": "Cielo Celos\u00eda Suspendido en Atrio",
    "category": "celosias",
    "categoryName": "Celos\u00edas Arquitect\u00f3nicas",
    "price": 5600,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/celosias/Suspended_wood_lattice_ceiling_d_2K_20261002115906.jpg",
    "gallery": [
      "assets/celosias/Suspended_wood_lattice_ceiling_d_2K_20261002115906.jpg",
      "assets/celosias/Walnut_wood_divider_panel_2K_20261002115459.jpg",
      "assets/celosias/Walnut_wood_divider_panel_photog_2K_20261002104634.jpg",
      "assets/celosias/Wood_lattice_ceiling_in_atrium_2K_20261002120034.jpg"
    ],
    "description": "Sistema celos\u00eda suspendido para plafones y cielos en lobbies, restaurantes y salas de alta gama.",
    "available": true,
    "customizable": true,
    "sku": "BUF-CEL-003",
    "material": "Madera de Nogal / Subestructura de Acero",
    "dimensions": "Dise\u00f1o modular contiguo",
    "leadTime": "15 a 20 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Plaf\u00f3n Escult\u00f3rico"
  },
  {
    "id": "prod-fac-001",
    "name": "Fachada Ventilada con Louvers Met\u00e1licos",
    "category": "fachadas",
    "categoryName": "Fachadas & Louvers",
    "price": 6200,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/fachadas/Building_facade_with_metal_louvers_2K_20261002130457.jpg",
    "gallery": [
      "assets/fachadas/Building_facade_with_metal_louvers_2K_20261002130457.jpg",
      "assets/fachadas/Building_facade_with_perforated__2K_20261002134805.jpg",
      "assets/fachadas/Building_facade_with_rusted_stee_2K_20261002130534.jpg",
      "assets/fachadas/Metal_louvre_system_advertising__2K_20261002130445.jpg",
      "assets/fachadas/Modern_building_facade_with_latt_2K_20261002134914.jpg"
    ],
    "description": "Envolvente arquitect\u00f3nica de fachadas con lamas met\u00e1licas de alto perfil y cortasoles perforados.",
    "available": true,
    "customizable": true,
    "sku": "BUF-FAC-001",
    "material": "Aluminio Extruido / Acero Corten",
    "dimensions": "M\u00f3dulos verticales a medida del proyecto",
    "leadTime": "20 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Fachada Comercial"
  },
  {
    "id": "prod-fac-002",
    "name": "Sistema Louver Plegable Residencial",
    "category": "fachadas",
    "categoryName": "Fachadas & Louvers",
    "price": 7400,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/fachadas/Modern_building_with_folding_lou_2K_20261002133915.jpg",
    "gallery": [
      "assets/fachadas/Modern_building_facade_with_meta_2K_20261002134758.jpg",
      "assets/fachadas/Modern_building_with_folding_lou_2K_20261002133915.jpg",
      "assets/fachadas/Modern_residential_facade_louver_2K_20261002132943.jpg",
      "assets/fachadas/Modern_residential_facade_louver_2K_20261002133308.jpg"
    ],
    "description": "Panel louver din\u00e1mico plegable para privacidad solar de balcones y ventanales residenciales.",
    "available": true,
    "customizable": true,
    "sku": "BUF-FAC-002",
    "material": "Aluminio Anodizado / Herrajes Industriales",
    "dimensions": "Desarrollo a medida del vano",
    "leadTime": "18 a 22 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Dynamic Louver"
  },
  {
    "id": "prod-acu-001",
    "name": "Paneles Ac\u00fasticos Ranurados para Muro",
    "category": "acustica",
    "categoryName": "Paneles Ac\u00fasticos & Plafones",
    "price": 3200,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/acustica/Acoustic_panels_on_wall_2K_20261002123921.jpg",
    "gallery": [
      "assets/acustica/Acoustic_panels_on_wall_2K_20261002123921.jpg",
      "assets/acustica/Acoustic_panels_on_wall_2K_20261002124005.jpg",
      "assets/acustica/Acoustic_panels_on_wall_2K_20261002124010.jpg",
      "assets/acustica/Architectural_wall_panels_in_bed_2K_20261002124209.jpg",
      "assets/acustica/Ceiling_baffles_in_corporate_lobby_2K_20261002120435.jpg",
      "assets/acustica/Ceiling_baffles_in_corporate_lobby_2K_20261002120512.jpg"
    ],
    "description": "Absorci\u00f3n ac\u00fastica arquitect\u00f3nica de alto rendimiento con perfiler\u00eda de madera de ingenier\u00eda y fieltro ac\u00fastico.",
    "available": true,
    "customizable": true,
    "sku": "BUF-ACU-001",
    "material": "MDF Enchapado Madera Natural + Fieltro PET Reciclado",
    "dimensions": "60 x 240 cm / 60 x 300 cm",
    "leadTime": "10 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Ac\u00fastica de Gran Formato"
  },
  {
    "id": "prod-acu-002",
    "name": "Baffles Ac\u00fasticos Suspendidos para Lobby",
    "category": "acustica",
    "categoryName": "Paneles Ac\u00fasticos & Plafones",
    "price": 4100,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/acustica/Ceiling_baffles_in_corporate_lobby_2K_20261002120435.jpg",
    "gallery": [
      "assets/acustica/Decorative_wall_panels_and_furni_2K_20261002124956.jpg",
      "assets/acustica/Decorative_wall_panels_in_bedroom_2K_20261002124201.jpg",
      "assets/acustica/Modern_wall_panels_with_furniture_2K_20261002125050.jpg",
      "assets/acustica/Red_ceiling_baffles_in_restaurant_2K_20261002121515.jpg",
      "assets/acustica/Suspended_ceiling_baffles_in_res_2K_20261002121730.jpg",
      "assets/acustica/Suspended_ceiling_lattices_in_re_2K_20261002121545.jpg"
    ],
    "description": "Baffles de plaf\u00f3n suspendidos de dise\u00f1o corporativo y comercial para control de eco y est\u00e9tica contempor\u00e1nea.",
    "available": true,
    "customizable": true,
    "sku": "BUF-ACU-002",
    "material": "Lama de Madera Tratada / N\u00facleo Ac\u00fastico Mineral",
    "dimensions": "Longitudes de 120 cm a 300 cm",
    "leadTime": "12 a 15 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Plaf\u00f3n Corporativo"
  },
  {
    "id": "prod-bar-001",
    "name": "Barandal de Celos\u00eda Corten con Pasamanos de Roble",
    "category": "barandales",
    "categoryName": "Barandales & Pasamanos",
    "price": 3600,
    "currency": "$",
    "unit": "ml",
    "image": "assets/barandales/Close-up_of_stair_railing_2K_20261002132158.jpg",
    "gallery": [
      "assets/barandales/Close-up_of_stair_railing_2K_20261002132158.jpg",
      "assets/barandales/Modern_wooden_staircase_with_met_2K_20261002132355.jpg",
      "assets/barandales/Staircase_railing_with_wooden_ha_2K_20261002132201.jpg"
    ],
    "description": "Sistema de barandal modular calado con corte CNC de precisi\u00f3n en acero estructural o corten y pasamanos anat\u00f3mico de madera.",
    "available": true,
    "customizable": true,
    "sku": "BUF-BAR-001",
    "material": "Acero Corten / Madera de Roble Macizo",
    "dimensions": "M\u00f3dulos de 100 cm alto x largo del proyecto",
    "leadTime": "15 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Barandales CNC"
  },
  {
    "id": "prod-pue-001",
    "name": "Puerta Principal de Acero Corten Calado",
    "category": "puertas-corten",
    "categoryName": "Puertas de Acero Corten",
    "price": 14500,
    "currency": "$",
    "unit": "pieza",
    "image": "assets/puertas/Corten_steel_door_with_cutouts_2K_20261002133320.jpg",
    "gallery": [
      "assets/puertas/Corten_steel_door_with_cutouts_2K_20261002133320.jpg",
      "assets/puertas/Corten_steel_door_with_cutouts_2K_20261002133428.jpg",
      "assets/puertas/Corten_steel_exterior_access_door_2K_20261002133329.jpg",
      "assets/puertas/Modern_residential_entrance_door_2K_20261002131648.jpg"
    ],
    "description": "Puerta de acceso de gran formato fabricada en Acero Corten oxidado de forma natural con celos\u00eda calada de seguridad.",
    "available": true,
    "customizable": true,
    "sku": "BUF-PUE-001",
    "material": "Acero Corten Patinado / N\u00facleo Aislante",
    "dimensions": "120 x 240 cm / 150 x 300 cm",
    "leadTime": "20 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Alta Seguridad & Est\u00e9tica"
  },
  {
    "id": "prod-lam-001",
    "name": "Lambr\u00edn Arquitect\u00f3nico de Listones de Madera",
    "category": "lambrin",
    "categoryName": "Lambrines & Revestimientos",
    "price": 2950,
    "currency": "$",
    "unit": "m\u00b2",
    "image": "assets/lambrin/LAMBRIN.jpg",
    "gallery": [
      "assets/lambrin/LAMBRIN.jpg",
      "assets/lambrin/Wall_cladding_with_minimalist_fu_2K_20261002125001.jpg"
    ],
    "description": "Revestimiento vertical continuo de listones en madera natural para interiores residenciales y ejecutivos.",
    "available": true,
    "customizable": true,
    "sku": "BUF-LAM-001",
    "material": "Nogal Americano / Pino Estructural Tratado",
    "dimensions": "Paneles ensamblables machihembrados",
    "leadTime": "8 a 12 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Revestimiento Premium"
  },
  {
    "id": "prod-int-001",
    "name": "Divisi\u00f3n Celos\u00eda de Espacios Interiores",
    "category": "biombos-y-cabeceras",
    "categoryName": "Biombos, Cabeceras & Espacios",
    "price": 5200,
    "currency": "$",
    "unit": "pieza",
    "image": "assets/interiores/Modern_luxury_interior_design_2K_20261002115438.jpg",
    "gallery": [
      "assets/interiores/Architectural_ceiling_design_wit_2K_20261002115733.jpg",
      "assets/interiores/Cabinet_with_perforated_metal_lo_2K_20261002132024.jpg",
      "assets/interiores/Children_s_play_space_interior_d_2K_20261002120546.jpg",
      "assets/interiores/Luxury_children_play_space_interior_2K_20261002120632.jpg",
      "assets/interiores/Modern_luxury_interior_design_2K_20261002115438.jpg",
      "assets/interiores/Person_reading_in_luxury_room_2K_20261002131628.jpg",
      "assets/interiores/Woman_leaning_against_corridor_wall_2K_20261002131340.jpg",
      "assets/interiores/Woman_leaning_against_corridor_wall_2K_20261002131422.jpg"
    ],
    "description": "Divisor calado para separaci\u00f3n de ambientes en suites, restaurantes y residencias de lujo.",
    "available": true,
    "customizable": true,
    "sku": "BUF-INT-001",
    "material": "Madera Noble / Estructura Interna Acero Oculto",
    "dimensions": "Fabrica a medida",
    "leadTime": "14 d\u00edas h\u00e1biles",
    "featured": true,
    "badge": "Dise\u00f1o de Interiores"
  },
  {
    "id": "prod-cat-001",
    "name": "Cat\u00e1logo de Patrones Geom\u00e9tricos Buffalo B12-B23",
    "category": "celosias",
    "categoryName": "Celos\u00edas Arquitect\u00f3nicas",
    "price": 0,
    "currency": "$",
    "unit": "Cotizaci\u00f3n",
    "image": "assets/catalogos/b12.jpg",
    "gallery": [
      "assets/catalogos/b12.jpg",
      "assets/catalogos/b13.jpg",
      "assets/catalogos/b14.jpg",
      "assets/catalogos/b15.jpg",
      "assets/catalogos/b16.jpg",
      "assets/catalogos/b17.jpg",
      "assets/catalogos/b18.jpg",
      "assets/catalogos/b19.jpg",
      "assets/catalogos/b20.jpg",
      "assets/catalogos/b21.jpg",
      "assets/catalogos/b22.jpg",
      "assets/catalogos/b23.jpg",
      "assets/catalogos/Gemini_Generated_Image_la9dqla9dqla9dql.jpg"
    ],
    "description": "Colecci\u00f3n completa de 12 patrones param\u00e9tricos exclusivos Buffalo para corte CNC en metal, MDF, resina o madera.",
    "available": true,
    "customizable": true,
    "sku": "BUF-CAT-B1223",
    "material": "Patrones Vectoriales / Fabricaci\u00f3n Multimaterial",
    "dimensions": "Cualquier escala y desarrollo",
    "leadTime": "Inmediata previa aprobaci\u00f3n",
    "featured": true,
    "badge": "Colecci\u00f3n de Patrones"
  }
];

function getProducts() {
  return BUFFALO_PRODUCTS;
}

function getProductById(id) {
  return BUFFALO_PRODUCTS.find(p => p.id === id);
}
